DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS orders;

CREATE TABLE customers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL
);

CREATE TABLE orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item TEXT NOT NULL,
  item_price FLOAT NOT NULL,
  customer_id BIGINT REFERENCES customers(id)
);