DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customers;

CREATE TABLE orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item TEXT NOT NULL,
  price INT NOT NULL
);

CREATE TABLE customer (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id = BIGINT REFERENCES orders(id)
);